### PR TITLE
[Display_01] Define StatelliteSignalCheckRequestTests

### PR DESCRIPTION
**Pull request by John-A11**
Working on #51 
Added tests to the test class StatelliteSignalCheckRequestTests

### CODE REVIEW

**Review by andrewdimmer — APPROVED** [review]
Looks good to me! Double check Eric and Steve don't have any changes they want made, then you're all set to merge!

**Review by EC01EC — APPROVED** [review]
Looks good

**Review by stevecatherman — APPROVED** [review]
:)

**Review by EC01EC — APPROVED** [review]
yep

**Review by stevecatherman — APPROVED** [review]
:)  :)

**Comment by andrewdimmer** [comment]
Issue with Code Owners. Re-running PlantUML Generation to try and resolve.

**Comment by andrewdimmer** [comment]
Running a nuclear merge and overriding approver because it looks like something lower down broke, and this should fix it.

**Pull request merged**
